### DISCUSSION TITLE
👀 Look what batch inscribe unlocked 🔓

### DISCUSSION THREAD

**Discussion by elocremarc** [ordinals/ord#2594] [Show and tell]
Now you can make circular dependent recursion work with batch inscriptions because you can deterministically know the Id of any dependency in your batch. 

Example:
```html
<!DOCTYPE html>
<html>
<head>
  <script>
    window.onload = function() {
      const id = window.location.pathname.split('/').pop();
      const tx = id.slice(0, -2);
      const scriptLink = `/content/${tx}i1`;
      const styleLink = `/content/${tx}i2`;

      const scriptElem = document.createElement('script');
      scriptElem.src = scriptLink;
      document.head.appendChild(scriptElem);

      const styleElem = document.createElement('link');
      styleElem.rel = 'stylesheet';
      styleElem.href = styleLink;
      document.head.appendChild(styleElem);
    };
  </script>
</head>
<body>
</body>
</html>
``` 

Batch Yaml
```yaml
mode: shared-output

inscriptions:
  - file: html.html
  - file: script.js
  - file: style.css
```
