### ISSUE TITLE
Batch file fields sometimes need reordering

### ISSUE THREAD

**Issue by raphjaph** [ordinals/ord#2849]
Sometime `ord` insists that `inscriptions` field should be at the first line and then the `mode` has to be put at the end. No idea why, probably something with `serde`

```yaml
mode: separate-outputs

inscriptions
  - file: ....
  - file: ....
  - file: ...
```
