### ISSUE TITLE
For local run, supply shows incorrect amount, supply should be 2000

### ISSUE THREAD

**Issue by twosatsmaxi** [ordinals/ord#3601]
<img width="747" alt="image" src="https://github.com/ordinals/ord/assets/112330467/12a011bb-c092-4fdd-844a-81d8204e320b">

## How to reproduct?
Etch locally using following file:
```
inscriptions:
- delegate: null
  destination: null
  file: env/inscription.txt
  metadata: null
  metaprotocol: null
  satpoint: null
mode: separate-outputs
parent: null
postage: null
reinscribe: false
etching:
  divisibility: 0
  premine: '1000'
  rune: FOOOOOOOOOOOOOOOOOOO
  supply: '2000'
  symbol: '¢'
  terms:
    amount: '1000'
    cap: 1
    height: null
    offset: null
  turbo: false
sat: null
satpoint: null

```

**Comment by twosatsmaxi** [comment]
Wait, does it show remaining supply?

**Comment by twosatsmaxi** [comment]
No, looks like a bug. It always shows premine value.
```
inscriptions:
- delegate: null
  destination: null
  file: env/inscription.txt
  metadata: null
  metaprotocol: null
  satpoint: null
mode: separate-outputs
parent: null
postage: null
reinscribe: false
etching:
  divisibility: 0
  premine: '1000'
  rune: FOOOOOOOOOOOODUPLI
  supply: '20000'
  symbol: '¢'
  terms:
    amount: '1000'
    cap: 19
    height: null
    offset: null
  turbo: false
sat: null
satpoint: null
```
<img width="578" alt="image" src="https://github.com/ordinals/ord/assets/112330467/97b2d8ac-d0a3-4048-9318-d7def1c4e8e4">
