### ISSUE TITLE
Delegate option returns error.

### ISSUE THREAD

**Issue by 0AAK0** [ordinals/ord#3671]
Hi guys,

I'm trying to etch a Rune using the delegate option instead of inscribing new photo for the Rune, but I get below error:
![image](https://github.com/ordinals/ord/assets/3874112/8f091614-e341-414e-9bd3-d782273a4ec6)

Moreover, the destination option is where the "Premine" will be sent or not? if not how to send the "Premine" to a different address?

This is my batch file (I did comment the unnecessary stuff):
```
# example batch file

# inscription modes:
# - `same-sat`: inscribe on the same sat
# - `satpoints`: inscribe on the first sat of specified satpoint's output
# - `separate-outputs`: inscribe on separate postage-sized outputs
# - `shared-output`: inscribe on a single output separated by postage
mode: separate-outputs

# parent inscription:
parent: 6ac5cacb768794f4fd7a78bf00f2074891fce68bd65c4ff36e77177237aacacai0

# postage for each inscription:
postage: 546

# allow reinscribing
reinscribe: true

# sat to inscribe on, can only be used with `same-sat`:
# sat: 5000000000

# rune to etch (optional)
etching:
  # rune name
  rune: XXXXXXXXXXX
  # allow subdividing super-unit into `10^divisibility` sub-units
  divisibility: 0
  # premine
  premine: 20000.00
  # total supply, must be equal to `premine + terms.cap * terms.amount`
  supply: 21000000.00
  # currency symbol
  symbol: 💰
  # mint terms (optional)
  terms:
    # amount per mint
    amount: 10490.00
    # maximum number of mints
    cap: 2000
    # mint start and end absolute block height (optional)
    # height:
    #   start: 840000
    #   end: 850000
    # # mint start and end block height relative to etching height (optional)
    # offset:
    #   start: 1000
    #   end: 9000
  # future runes protocol changes may be opt-in. this may be for a variety of
  # reasons, including that they make light client validation harder, or simply
  # because they are too degenerate.
  #
  # setting `turbo` to `true` opts in to these future protocol changes,
  # whatever they may be.
  turbo: true

# inscriptions to inscribe
 inscriptions:
  # path to inscription content
  #- file: 
  # inscription to delegate content to (optional)
  delegate: 1e7fbc827236134e2ecb19d91b07ad2e4d96445d43515349a01532869f8a21dai7
  # destination (optional, if no destination is specified a new wallet change address will be used)
  destination: bc1p52nn3k5fsjpkaje9gupvlypyjzd44j03tkyxeaga3m8msrf6m5zs6d9ucq
  # inscription metadata (optional)
#  # metadata:
#    # title: Delicious Mangos
#    # description: >
#       Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam semper,
#       ligula ornare laoreet tincidunt, odio nisi euismod tortor, vel blandit
#       metus est et odio. Nullam venenatis, urna et molestie vestibulum, orci
#       mi efficitur risus, eu malesuada diam lorem sed velit. Nam fermentum
#       dolor et luctus euismod.

# - file: token.json
#   # inscription metaprotocol (optional)
#   metaprotocol: DOPEPROTOCOL-42069

# - file: tulip.png
#   destination: bc1pdqrcrxa8vx6gy75mfdfj84puhxffh4fq46h3gkp6jxdd0vjcsdyspfxcv6
#   metadata:
#     author: Satoshi Nakamoto
```
