### ISSUE TITLE
Etch new rune with exists parent inscription?

### ISSUE THREAD

**Issue by lugondev** [ordinals/ord#3693]
Is it possible?

**Comment by cryptoni9n** [comment]
> Is it possible?

Hi lugondev - if you're asking if we can etch a new rune with an existing parent inscription, the answer is yes.  There is a parent field near the top of the batch.yaml (https://github.com/ordinals/ord/blob/master/batch.yaml) that you can supply with the inscription ID of the parent you want to make a child for.

**Comment by lugondev** [comment]
I dont think so!
That parent is used for child inscription, not for Rune!
Have you tried it? which tx or etched Rune did you make?

**Comment by cryptoni9n** [comment]
> I dont think so!
> That parent is used for child inscription, not for Rune!
> Have you tried it? which tx or etched Rune did you make?

I'm sorry, I misunderstood what you were asking. 

Are you asking if you can etch a rune with a parent that already exists on chain? I use the delegate feature for this but that may not be what you want.

Does that not work for your use case because a new inscription ID is created and you prefer to simply link to the existing inscription as the parent?

**Comment by lugondev** [comment]
right, I wanna use one inscription to create some runes, like collection!

**Comment by cryptoni9n** [comment]
ok - have you seen any runes that have this type of provenance? I don't think this is currently possible with ord - let me explain why.

When etching a new rune, you have the ability to include a command within the batch that inscribes an inscription along with the rune genesis.  This inscription becomes attached to the rune, and vice versa, as they were created in the same transaction which ensures the relationship.  While it is not specifically called a parent/child relationship, in effect, that is what it is.  The inscription appears atop the rune, as a parent would.  The inscription carries a link to the rune, as if it were its child.  

Essentially, inscribing the inscription with the etching is the method of providing a parent for the rune.  I understand that you would like to create the same type of relationship, but not have to inscribe a new parent and instead point at an existing one.  In other words, not only do you want to be able to specify a parent for the inscription that is inscribed during the etch, but you want to provide a parent inscription for the rune etching itself, a **runeparent:** field in the yaml.

Can you confirm that this deeper explanation is keeping with what you're asking for?

**Comment by twosatsmaxi** [comment]
@lugondev you can actually, in batch.yaml you'll have to mention the `parent`, just tried it in the regtest.
<img width="903" alt="image" src="https://github.com/ordinals/ord/assets/112330467/a224f468-0ae2-4bf8-a01d-819a3a1428fe">

```
inscriptions:
- delegate: null
  destination: null
  metadata: null
  metaprotocol: null
  satpoint: null
mode: separate-outputs
parent: e271967c1520ac54f699ba65ef95b906b49d83bc70edbbe17e77a8d1a3143f29i0
postage: null
reinscribe: false
etching:
  divisibility: 0
  premine: '1000'
  rune: FOOFOOFOOWITHPARENT
  supply: '2000'
  symbol: '¢'
  terms:
    amount: '1000'
    cap: 1
    height: null
    offset: null
  turbo: false
sat: null
satpoint: null
```
