### ISSUE TITLE
Permissioned Rune minting

### ISSUE THREAD

**Issue by lifofifoX** [ordinals/ord#3995]
Any thoughts on utilizing parent child provenance to restrict who can mint a Rune?

Following 3 options associated with etching inscription (say, first inscription revealed in etching tx) provenance could offer a wide range of options to the etcher.

- **self** - Etching inscription must be an input to the mint transaction.
- **children** - A child inscription of etching inscription must be an input to the mint transaction.
- **siblings** - A child inscription of etching inscription's parent(s) must be an input to the mint transaction.

Example:

```yaml
parents:
- 6ac5cacb768794f4fd7a78bf00f2074891fce68bd65c4ff36e77177237aacacai0

etching:
  rune: THE•BEST•RUNE
  divisibility: 2
  premine: 1000.00
  supply: 10000.00
  symbol: $
  terms:
    amount: 100.00
    cap: 90
    restrict: self | children | siblings

inscriptions:
- file: mango.avif
```

- **self** - `mango.avif` inscription must be an input to the mint transaction.
- **children** - A child inscription of `mango.avif` inscription must be an input to the mint transaction.
- **siblings** - A child inscription of `6ac5cacb768794f4fd7a78bf00f2074891fce68bd65c4ff36e77177237aacacai0`, parent of `mango.avif` inscription, must be an input to the mint transaction.

Premine can be disallowed for `children` restriction.
